import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const header = fs.readFileSync(path.join(root, 'components', 'header.html'), 'utf8').trim();
const footer = fs.readFileSync(path.join(root, 'components', 'footer.html'), 'utf8').trim();
const baseUrl = 'https://serialcriminologist.ca';
const placeholderPages = new Set([
  'courses.html',
  'essays.html',
  'manuscripts.html',
  'memes.html',
  'op-eds.html',
  'opportunities.html',
  'podcast.html',
  'reels.html',
  'resources.html',
  'substack.html'
]);
const redirectPages = new Set([
  'approach.html',
  'criminology.html',
  'media-engagement.html',
  'received-view.html'
]);

function decodeHtml(value) {
  return value
    .replaceAll('&amp;', '&')
    .replaceAll('&quot;', '"')
    .replaceAll('&#39;', "'")
    .replaceAll('&middot;', '·');
}

function schemaFor(file, title, description, canonical) {
  const person = {
    '@type': 'Person',
    '@id': `${baseUrl}/#person`,
    name: 'Dr. Wade Deisman',
    jobTitle: 'Criminologist',
    url: `${baseUrl}/about.html`
  };

  if (file === 'index.html') {
    return {
      '@context': 'https://schema.org',
      '@graph': [
        {
          '@type': 'WebSite',
          '@id': `${baseUrl}/#website`,
          url: `${baseUrl}/`,
          name: 'Serial Criminologist',
          description,
          inLanguage: 'en-CA',
          publisher: { '@id': `${baseUrl}/#person` }
        },
        person
      ]
    };
  }

  const pageType = file === 'about.html' ? 'ProfilePage' : file === 'contact.html' ? 'ContactPage' : 'WebPage';
  return {
    '@context': 'https://schema.org',
    '@type': pageType,
    '@id': `${canonical}#webpage`,
    url: canonical,
    name: title,
    description,
    inLanguage: 'en-CA',
    isPartOf: { '@id': `${baseUrl}/#website` },
    author: { '@id': `${baseUrl}/#person` },
    primaryImageOfPage: { '@type': 'ImageObject', url: `${baseUrl}/assets/social-card.png` }
  };
}

function socialBlock({ file, title, description, canonical }) {
  const robots = placeholderPages.has(file) ? '  <meta name="robots" content="noindex, follow">\n' : '';
  const schema = schemaFor(file, title, description, canonical);
  return `  <!-- Social metadata: generated by scripts/build.mjs -->
${robots}  <meta name="author" content="Dr. Wade Deisman">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="Serial Criminologist">
  <meta property="og:locale" content="en_CA">
  <meta property="og:title" content="${title.replaceAll('"', '&quot;')}">
  <meta property="og:description" content="${description.replaceAll('"', '&quot;')}">
  <meta property="og:url" content="${canonical}">
  <meta property="og:image" content="${baseUrl}/assets/social-card.png">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta property="og:image:alt" content="Serial Criminologist, evidence over anecdote">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="${title.replaceAll('"', '&quot;')}">
  <meta name="twitter:description" content="${description.replaceAll('"', '&quot;')}">
  <meta name="twitter:image" content="${baseUrl}/assets/social-card.png">
  <link rel="icon" href="assets/favicon.svg" type="image/svg+xml">
  <script type="application/ld+json">
${JSON.stringify(schema, null, 2)}
  </script>
  <!-- /Social metadata -->
`;
}

for (const file of fs.readdirSync(root).filter((name) => name.endsWith('.html'))) {
  if (redirectPages.has(file)) continue;
  const filePath = path.join(root, file);
  let source = fs.readFileSync(filePath, 'utf8');
  if (!source.includes('<main id="main-content">')) continue;

  source = source
    .replace(/<header class="site-header">[\s\S]*?<\/header>/, header)
    .replace(/<footer class="site-footer">[\s\S]*?<\/footer>/, footer)
    .replace(/\s*<script src="js\/main\.js"><\/script>\s*/g, '\n')
    .replace(/\s*<!-- Social metadata: generated by scripts\/build\.mjs -->[\s\S]*?<!-- \/Social metadata -->\s*/g, '\n')
    .replace(/<meta name="robots" content="noindex, follow">\s*/g, '')
    .replace(/href="css\/styles\.css(?:\?v=[^"]+)?"/g, 'href="css/styles.css?v=20260709"');

  if (file === 'index.html') {
    source = source.replace(
      /<link rel="canonical" href="https:\/\/serialcriminologist\.ca\/index\.html">/,
      '<link rel="canonical" href="https://serialcriminologist.ca/">'
    );
  }

  const titleMatch = source.match(/<title>([^<]+)<\/title>/);
  const descriptionMatch = source.match(/<meta name="description" content="([^"]+)">/);
  const canonicalMatch = source.match(/<link rel="canonical" href="([^"]+)">/);
  if (!titleMatch || !descriptionMatch || !canonicalMatch) {
    throw new Error(`Missing metadata required to build ${file}`);
  }

  const title = decodeHtml(titleMatch[1].trim());
  const description = decodeHtml(descriptionMatch[1].trim());
  const canonical = canonicalMatch[1];
  const metadata = socialBlock({ file, title, description, canonical });
  source = source.replace(descriptionMatch[0], `${descriptionMatch[0]}\n${metadata.trimEnd()}`);
  source = source.replace('</body>', '  <script src="js/main.js"></script>\n</body>');
  fs.writeFileSync(filePath, source, 'utf8');
}

let sitemap = fs.readFileSync(path.join(root, 'sitemap.xml'), 'utf8');
sitemap = sitemap.replace('<loc>https://serialcriminologist.ca</loc>', '<loc>https://serialcriminologist.ca/</loc>');
for (const file of placeholderPages) {
  const escaped = file.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  sitemap = sitemap.replace(new RegExp(`\\s*<url>\\s*<loc>${baseUrl}/${escaped}<\\/loc>[\\s\\S]*?<\\/url>`), '');
}
fs.writeFileSync(path.join(root, 'sitemap.xml'), `${sitemap.trim()}\n`, 'utf8');

console.log('Built shared layout, metadata, structured data, and sitemap.');
